-- Supabase Schema for System Design Arena
-- This script creates the necessary tables for the application.

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Table: users (we will rely on Supabase Auth's users table, but we can create a profile table)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  avatar_url text,
  subscription_status text default 'free' check (subscription_status in ('free', 'yearly', 'sbc')),
  stripe_customer_id text,
  stripe_subscription_id text,
  sbc_member_email text,
  sims_used_today integer default 0,
  last_sim_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using (true);

create policy "Users can insert their own profile."
  on profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on profiles for update
  using (auth.uid() = id);

-- Table: problems
create table if not exists problems (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  tags text[] default '{}',
  brief text not null,
  requirements text not null,
  key_considerations text not null,
  reference_architecture text,
  "order" integer default 0,
  is_public boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: design_sessions
create table if not exists design_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  problem_id bigint references problems on delete set null,
  session_uuid uuid default uuid_generate_v4() unique not null,
  status text default 'in_progress' check (status in ('in_progress', 'completed')),
  speed_setting double precision default 1.0,
  traffic_setting double precision default 1.0,
  read_write_ratio double precision default 0.92,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: canvas_nodes
create table if not exists canvas_nodes (
  id bigint generated by default as identity primary key,
  session_id bigint references design_sessions on delete cascade not null,
  node_uuid uuid default uuid_generate_v4() unique not null,
  component_type text not null,
  label text,
  x double precision not null default 0,
  y double precision not null default 0,
  replicas integer not null default 1,
  implementation_notes text,
  is_disabled boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: canvas_edges
create table if not exists canvas_edges (
  id bigint generated by default as identity primary key,
  session_id bigint references design_sessions on delete cascade not null,
  edge_uuid uuid default uuid_generate_v4() unique not null,
  source_node_id bigint references canvas_nodes on delete cascade not null,
  target_node_id bigint references canvas_nodes on delete cascade not null,
  label text,
  style text check (style in ('solid', 'dashed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: chaos_logs
create table if not exists chaos_logs (
  id bigint generated by default as identity primary key,
  session_id bigint references design_sessions on delete cascade not null,
  chaos_event_id text not null,
  target_node_id bigint references canvas_nodes on delete set null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  result jsonb
);

-- Table: score_results
create table if not exists score_results (
  id bigint generated by default as identity primary key,
  session_id bigint references design_sessions on delete cascade not null,
  user_id uuid references auth.users on delete set null,
  judge_rigor_score integer,
  judge_pragmatism_score integer,
  consensus_verdict text check (consensus_verdict in ('pass', 'fail', 'borderline')),
  written_feedback text,
  debate_summary text,
  model_used text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: articles
create table if not exists articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  category text not null check (category in ('foundations', 'feeds-storage', 'realtime-geo')),
  summary text not null,
  content text not null,
  featured boolean default false,
  related_problem_ids bigint[] default '{}',
  "order" integer default 0,
  is_published boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable real-time for all tables (optional, but useful for future features)
alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table problems;
alter publication supabase_realtime add table design_sessions;
alter publication supabase_realtime add table canvas_nodes;
alter publication supabase_realtime add table canvas_edges;
alter publication supabase_realtime add table chaos_logs;
alter publication supabase_realtime add table score_results;
alter publication supabase_realtime add table articles;