version: "3.8"

services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3030
      - NEXT_PUBLIC_SUPABASE_URL=http://192.168.0.124:8000
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
